repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
        name: "âœ… json Â· Check Json"
        stages: [pre-commit]
      - id: pretty-format-json
        name: "âœ… json Â· Pretty Format Json"
        stages: [pre-commit]
        exclude: "^notebooks/|.ipynb$"
        args:
          - --autofix
          - --no-sort-keys
      - id: end-of-file-fixer
        name: "âœ… EOF Â· End of File Fixer"
        stages: [pre-commit]
      - id: trailing-whitespace
        name: "âœ… Whitespaces Â· Trailing Whitespaces"
        stages: [pre-commit]
      - id: check-merge-conflict
        name: "ğŸŒ³ git Â· Detect conflict markers"
      - id: check-added-large-files
        name: "ğŸŒ³ git Â· Block large file commits"
        args: ['--maxkb=5000']
      - id: debug-statements
        name: "ğŸ python Â· Check debug statemens"
        stages: [pre-commit]
        exclude: "^scripts/"
        language_version: python3.12
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.31.0
    hooks:
      - id: check-github-workflows
        name: "ğŸ™ github-actions Â· Validate gh workflow files"
        args: ["--verbose"]
      - id: check-taskfile
        name: "âœ… taskfile Â· Validate Task configuration"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff-format
        name: "ğŸ python Â· Format with Ruff"
        types_or: [ python, pyi ]
      - id: ruff
        name: "ğŸ python Â· Fix with Ruff"
        stages: [pre-commit]
        types_or: [ python, pyi ]
        args:
          - --fix
          - --exit-non-zero-on-fix
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.403
    hooks:
      - id: pyright
        name: "ğŸ python Â· Check types"
  # - repo: https://github.com/srstevenson/nb-clean
  #   rev: 2.4.0
  #   hooks:
  #     - id: nb-clean
  #       name: "ğŸ python Â· Clean Notebooks"
  #       stages: [pre-commit]
  #       args:
  #         - --remove-empty-cells
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.9
    hooks:
      - id: uv-lock
        name: "ğŸ”’ uv Â· Check the lock consistency"
        args: ["--check"]
